name: wt_data_visualiser
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_data_visualiser
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  animated_tree_view:
  flutter:
    sdk: flutter
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

#dependency_overrides:

flutter:
