name: wt_data_visualiser_examples
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation:
  wt_data_visualiser:
    git:
      url: https://github.com/tmcmaster/wt_data_visualiser.git
  wt_firepod:
    git:
      url: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git

dependency_overrides:
  wt_data_visualiser:
    path: ..

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

flutter:
  uses-material-design: true